apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels: 
    app: backend
  annotations: 
    "sidecar.jaegertracing.io/inject": "true"  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: barhome/dashboard-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer