apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels: frontend
  annotations: 
    "sidecar.jaegertracing.io/inject": "true"  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: barhome/dashboard-frontend:latest
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer