apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
  labels:
    app: trial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        image: barhome/dashboard-trial:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
spec:
  selector:
    app: trial
  ports:
    - port: 8082
      targetPort: 8080
  type: LoadBalancer
